version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
    vulnerability-alerts:
      enabled: true
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "security"
      - "javascript"
  
  - package-ecosystem: "pip"
    directory: "backend"
    schedule:
      interval: "daily"
    vulnerability-alerts:
      enabled: true
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "security"
      - "python"
  
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "daily"
    vulnerability-alerts:
      enabled: true
    open-pull-requests-limit: 3
