---
- name: Create application directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: "0755"

- name: Deploy docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: "0644"

- name: Ensure Docker Compose stack is up
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
    pull: yes
    restart: yes
    recreate: smart
    stopped: no
