---
- name: Установка зависимостей
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Создание директории для ключей
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Добавление GPG-ключа Docker (официальный ключ для Ubuntu)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Добавление репозитория Docker для Ubuntu 22.04 (Jammy)
  apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      jammy stable
    filename: docker.list
    update_cache: yes

- name: Установка Docker и компонентов
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
