---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  tags: docker

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: docker

- name: Add Docker's official GPG key (only if changed)
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: no
  register: docker_key
  tags: docker

- name: Add Docker repository (only if key changed or first run)
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    update_cache: yes
    update_cache: "{{ docker_key.changed }}"
    state: present
  tags: docker

- name: Install Docker packages
  apt:
    name:
      #- docker-ce
      #- docker-ce-cli
      - docker
      - docker.io
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  tags: docker
