---
- name: Deploy full stack
  hosts: web
  become: yes
  vars_files:
    - group_vars/all.yml

  roles:
    # Докер ставьте заранее сами
    # https://docs.docker.com/engine/install/ubuntu/
    - role: nginx
      tags: nginx
    - role: app_stack
      tags: app_stack

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        
    - name: Restart PostgreSQL
      service:
        name: "postgresql@{{ postgres_version }}-main"
        state: restarted
        
    - name: Restart Redis
      service:
        name: redis-server
        state: restarted
