permissions:
  contents: read
name: Tests

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  unit_test:
    name: Unit Tests vs Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: cd backend && ./setup_requirements.sh --qa

      - name: Run tests
        run: |
          cd backend
          pytest --cov --cov-branch --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  mutation_test:
    name: Mutation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: cd backend && ./setup_requirements.sh --qa

      - name: Run tests
        run: |
          cd backend
          #pytest --cov --cov-branch --cov-report=xml
          python3 manage.py makemigrations --settings=config.local
          python3 manage.py migrate --settings=config.local
          #python3 manage.py muttest api communication core --settings=config.local
          #mutatest -s ./core -t "pytest"
          mutatest -s ./core -t "pytest --nomigrations" --nocov
