name: Build and Deploy a new version

on:
  push:
    branches: [ master ]

jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  read_version:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      version: ${{ steps.set_version.outputs.VERSION }}
    steps:
      - name: Read version
        id: set_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_OUTPUT

  # build_frontend:
  #   needs: read_version
